# Form implementation generated from reading ui file 'expense_manager.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6.QtWidgets import (
    QMainWindow, QWidget, QVBoxLayout, QHBoxLayout,
    QListWidget, QPushButton, QLineEdit
)
from PyQt6.QtCore import Qt

def setup_ui(self):
    # Настройка окна
    self.setWindowTitle("Менеджер расходов")
    self.setFixedSize(400, 500)

    # Основной виджет
    self.central_widget = QWidget()
    self.setCentralWidget(self.central_widget)

    # Левый список и правые кнопки
    self.list_widget = QListWidget()
    self.list_widget.setSelectionMode(QListWidget.SelectionMode.MultiSelection)
    self.list_widget.setStyleSheet("""
        QListWidget {
            border: 1px solid #aaa;
            font-size: 14px;
            padding: 5px;
        }
        QListWidget::item {
            padding: 5px;
        }
        QListWidget::item:selected {
            background-color: #d3d3d3;
            color: black;
        }
    """)

    self.add_category_button = QPushButton("Добавить категорию")
    self.add_expense_button = QPushButton("Добавить трату")
    self.delete_button = QPushButton("Удалить выбранное")
    self.analyze_button = QPushButton("Установить лимит")
    self.toggle_selection_mode_button = QPushButton("Режим выделения")
    self.import_csv_button = QPushButton("Импорт из CSV")
    self.export_csv_button = QPushButton("Экспорт в CSV")
    self.edit_item_button = QPushButton("Редактировать")
    self.calculate_totals_button = QPushButton("Суммы по категориям")
    self.sort_button = QPushButton("Отсортировать")
    self.reset_button = QPushButton("Сброс")

    # Поле поиска
    self.search_input = QLineEdit()
    self.search_input.setPlaceholderText("Поиск...")

    # Вертикальный компоновщик для кнопок
    button_layout = QVBoxLayout()
    button_layout.addWidget(self.search_input)
    button_layout.addWidget(self.add_category_button)
    button_layout.addWidget(self.add_expense_button)
    button_layout.addWidget(self.delete_button)
    button_layout.addWidget(self.edit_item_button)
    button_layout.addWidget(self.analyze_button)
    button_layout.addWidget(self.calculate_totals_button)
    button_layout.addWidget(self.import_csv_button)
    button_layout.addWidget(self.export_csv_button)
    button_layout.addWidget(self.toggle_selection_mode_button)
    button_layout.addWidget(self.sort_button)
    button_layout.addWidget(self.reset_button)
    button_layout.addStretch()

    # Горизонтальный компоновщик для списка и кнопок
    main_layout = QHBoxLayout()
    main_layout.addWidget(self.list_widget)
    main_layout.addLayout(button_layout)

    # Установка основного компоновщика
    self.central_widget.setLayout(main_layout)
